---
version: '2.1'

volumes:
    esdata:

services:
    es_db:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.8.8
        environment:
            discovery.type: single-node
            xpack.security.enabled: "false"
        ports:
            - "${ES_PORT1}:9200"
            - "${ES_PORT2}:9300"
        volumes:
            - esdata:/usr/share/elasticsearch/data
