---
version: '2.1'

volumes:
    esdata:

services:
    es_db:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.8.8
        environment:
            discovery.type: single-node
            xpack.security.enabled: "false"
        ports: ['9200:9200', '9300:9300']
        volumes:
            - esdata:/usr/share/elasticsearch/data
